### ISSUE TITLE
jackson annotations should go into separate jar

### ISSUE THREAD

**Issue by stepancheg** [resty-gwt/resty-gwt#236]
If user downloads both restygwt and jackson from Maven, they get two copies of jackson annotations in classpath, which may cause weird and hard to find problems.

restygwt should put annotations into separate jar, so it could be excluded when downloading dependencies.

**Comment by michael-newsrx** [comment]
yes.. having them inside the main resty jar causes conflicts with main jackson jars

**Comment by Marvman** [comment]
Should really be separated from resty.
Workaround is to remove the jackson stuff from the resty jar

**Comment by mkristian** [comment]
I added the jackson annotation jars as maven dependency including their sources. since I need feedback of whether this approach works or not I deployed the current snapshot to oss.sonatype.org:

https://oss.sonatype.org/content/repositories/snapshots/org/fusesource/restygwt/restygwt/

please add https://oss.sonatype.org/content/repositories/snapshots/ as snapshot repo to your pom
