### ISSUE TITLE
Query param of type Date does not get serialized using the date format specified in Defaults

### ISSUE THREAD

**Issue by aponyrko** [resty-gwt/resty-gwt#342]
The following method in RestServiceClassCreator gets used to generate code that in turn serializes query params:

```
    protected String toStringExpression(JType type, String expr) throws UnableToCompleteException {
        if (type.isPrimitive() != null) {
            return "\"\"+" + expr;
        }
        if (STRING_TYPE == type) {
            return expr;
        }

        if (type.isClass() != null &&
            isOverlayArrayType(type.isClass())) {
          return "(new " + JSON_ARRAY_CLASS + "(" + expr + ")).toString()";
        }
        if (type.isClass() != null &&
            OVERLAY_VALUE_TYPE.isAssignableFrom(type.isClass())) {
          return "(new " + JSON_OBJECT_CLASS + "(" + expr + ")).toString()";
        }

        return String.format("(%s != null ? %s.toString() : null)", expr, expr);
    }
```

Params of type Date fall through to the toString() call instead of using the date format specified by org.fusesource.restygwt.client.Defaults.

**Comment by freddyboucher** [comment]
@aponyrko 
I created a PR against your repo to add a JUnit test: https://github.com/aponyrko/resty-gwt/pull/1
A big thanks for your fix, I was working on this exact ticket before seeing you've already fixed it :)

**Comment by StevenDieu** [comment]
Hi,

We have an issue related to this development. There used to be a bug (Defaults date formatter ignored, which is addressed by this PR). Now, the date is correctly formatted, but with outer quotes.

See java.util.Objects.toString() => JSONString.toString() => JsonUtils.escapeValue()

Thus, the sent request contains the String ""2018-03-08T00:00:00.000+0100"" instead of "2018-03-08T00:00:00.000+0100".

I think its a real regression introduced by this commit.

**Comment by freddyboucher** [comment]
@StevenDieu 
I confirm the issue, I've added a JUnit test to illustrate it.
Will try to fix it this week.
